### ISSUE TITLE
Column name update/seeding tutorials

### ISSUE THREAD

**Issue by MarkMoretto** [WinVector/pyvtreat#11]
Hi.  I didn't want to fork the repo for this, but under the Python [classification example](https://github.com/WinVector/pyvtreat/blob/master/Examples/Classification/Classification.md) in the exploratory section, the notebook says:

`'Find the mean value of yc'`

I think 'yc' is a nominal column and finding the mean wouldn't be possible.  With that in mind, here's two friendly suggestions:

1. Add something like numpy.random.seed(42) or another seed value at the top of the examples for reproducibility by those following the tutorial.
2. Update the mean value sections.  I could be wrong and may have misread the document, but I went through another of the tutorials and some of the stuff copied over could have been mislabeled.

Other than that, the package looks interesting so far.

Thanks!

**Comment by JohnMount** [comment]
Definitely will update the documentation.  

The mean-value of y is well defined for logicals, and is the prevalence of the true class.  We will expand on that a bit and rewrite that as `numpy.mean(d['yc']) == outcome_target`.
