### ISSUE TITLE
Use with PySpark

### ISSUE THREAD

**Issue by dgenio** [WinVector/pyvtreat#17]
With the rise of Spark usage in the ML community, it would be interesting to have Vtreat been able to deal with Spark RDDs

**Comment by JohnMount** [comment]
That would be a nice extension, but will probably have to wait on one of our clients needing it. One possibility is basing a version of vtreat on https://github.com/WinVector/data_algebra , which allows one to re-base between Pandas and SQL for many systems (including Spark).

**Comment by JohnMount** [comment]
I now have a prototype implementation of translating a vtreat data treatment into data algebra. This allows further translation into many db dialects, including SparkSQL. Training is done in memory, on a sample if need be. The code and example is [here](https://github.com/WinVector/pyvtreat/blob/main/Examples/Database/vtreat_db_adapter.ipynb). It is new code, so I don't have a lot of experience with it yet. Direct relational integration (without SQL) would depend on such integration in data algebra (should be doable).
