### ISSUE TITLE
Question - How to encode high cardinal variables

### ISSUE THREAD

**Issue by SSMK-wq** [WinVector/pyvtreat#19]
I came across this package while I was googling to find a way to encode my high cardinal variables.

My categorical variable has 15 level and my dataset has only 900 rows.

I would like to encode them in a manner that will allow us to interpret later (unlike hash etc).

So, Is there any tutorial or method on how can we encode high cardinal variable without losing interpretability?

**Comment by JohnMount** [comment]
I can't always supply additional teaching material. But fortunately you are not in the "high cardinality case", so standard methods work well and can preserve interpretability.

With only 15 levels for 900 rows, one can safely use [sklearn.preprocessing.OneHotEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html), or  the "indicator_code" coder setting from vtreat (example [here](https://github.com/WinVector/pyvtreat/blob/master/Examples/Unsupervised/Unsupervised.md)).
