### ISSUE TITLE
Unspecified upper version limits for dependencies

### ISSUE THREAD

**Issue by DoubleGremlin181** [WinVector/pyvtreat#21]
**Issue**
The `setup.py` file does not specify upper version limits for any dependencies which can lead to major version upgrades with breaking changes.
**Impact**
This can be currently seen via `pandas` which recently got a major version bump. Upon release `vtreat==1.2.8` did not upgrade `pandas` to >=2.0.0, however it currently does.
**Potential Fix**
Specify approximate version number numbers using `~=` or upper limits using `<`

Note: Other than an unspecified upper limit in `vtreat`, `pandas` also indirectly gets a version bump through `data_algebra` which now requires `pandas>=2.0.0`

**Comment by DoubleGremlin181** [comment]
Thanks for looking into it! I do feel like upper bounds, even if they are broad, would be required to avoid such issues from occurring.

**Comment by JohnMount** [comment]
I have set upper and lower limits for all external dependencies, and weakened the connection to data_algebra to an extension/suggests role. I am targeting Pandas 2 (which I know is new).
